import turtle

screen = turtle.Screen()
screen.bgcolor("black")
screen.setup(1200, 800)

t = turtle.Turtle()
t.speed(0)
t.pensize(3)

def draw_A(x, y):
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.color("cyan")
    t.setheading(75)
    t.forward(60)
    t.right(150)
    t.forward(60)
    t.backward(20)
    t.right(105)
    t.forward(15)
    # 3D effect
    t.penup()
    t.goto(x + 3, y - 3)
    t.pendown()
    t.color("white")
    t.setheading(75)
    t.forward(60)

def draw_U(x, y):
    t.penup()
    t.goto(x, y + 50)
    t.pendown()
    t.color("cyan")
    t.setheading(270)
    t.forward(40)
    t.circle(10, 180)
    t.forward(40)
    # 3D effect
    t.penup()
    t.goto(x + 3, y + 47)
    t.pendown()
    t.color("white")
    t.setheading(270)
    t.forward(40)

def draw_D(x, y):
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.color("cyan")
    t.setheading(90)
    t.forward(50)
    t.right(90)
    t.circle(-25, 180)
    t.right(90)
    # 3D effect
    t.penup()
    t.goto(x + 3, y - 3)
    t.pendown()
    t.color("white")
    t.setheading(90)
    t.forward(50)

def draw_C(x, y):
    t.penup()
    t.goto(x + 25, y)
    t.pendown()
    t.color("cyan")
    t.setheading(180)
    t.circle(25, 180)
    # 3D effect
    t.penup()
    t.goto(x + 28, y - 3)
    t.pendown()
    t.color("white")
    t.setheading(180)
    t.circle(25, 90)

def draw_I(x, y):
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.color("cyan")
    t.setheading(0)
    t.forward(30)
    t.backward(15)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(15)
    t.backward(30)
    # 3D effect
    t.penup()
    t.goto(x + 3, y - 3)
    t.pendown()
    t.color("white")
    t.setheading(0)
    t.forward(30)

def draw_O(x, y):
    t.penup()
    t.goto(x, y + 25)
    t.pendown()
    t.color("cyan")
    t.circle(25)
    # 3D effect
    t.penup()
    t.goto(x + 3, y + 22)
    t.pendown()
    t.color("white")
    t.circle(25, 90)

def draw_S(x, y):
    t.penup()
    t.goto(x + 25, y + 10)
    t.pendown()
    t.color("cyan")
    t.setheading(180)
    t.circle(10, 180)
    t.circle(-10, 180)
    # 3D effect
    t.penup()
    t.goto(x + 28, y + 7)
    t.pendown()
    t.color("white")
    t.setheading(180)
    t.circle(10, 90)

def draw_T(x, y):
    t.penup()
    t.goto(x, y + 50)
    t.pendown()
    t.color("cyan")
    t.setheading(0)
    t.forward(40)
    t.backward(20)
    t.right(90)
    t.forward(50)
    # 3D effect
    t.penup()
    t.goto(x + 3, y + 47)
    t.pendown()
    t.color("white")
    t.setheading(0)
    t.forward(40)

def draw_E(x, y):
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.color("cyan")
    t.setheading(90)
    t.forward(50)
    t.right(90)
    t.forward(30)
    t.backward(30)
    t.right(90)
    t.forward(25)
    t.left(90)
    t.forward(20)
    t.backward(20)
    t.right(90)
    t.forward(25)
    t.left(90)
    t.forward(30)
    # 3D effect
    t.penup()
    t.goto(x + 3, y - 3)
    t.pendown()
    t.color("white")
    t.setheading(90)
    t.forward(50)

def draw_X(x, y):
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.color("cyan")
    t.setheading(45)
    t.forward(70)
    t.backward(35)
    t.right(90)
    t.forward(35)
    t.backward(70)
    # 3D effect
    t.penup()
    t.goto(x + 3, y - 3)
    t.pendown()
    t.color("white")
    t.setheading(45)
    t.forward(35)

# Draw "AUDACIOUS TEXT"
# AUDACIOUS
draw_A(-400, 100)
draw_U(-350, 100)
draw_D(-300, 100)
draw_A(-250, 100)
draw_C(-200, 100)
draw_I(-150, 100)
draw_O(-100, 100)
draw_U(-50, 100)
draw_S(0, 100)

# TEXT
draw_T(-150, 0)
draw_E(-100, 0)
draw_X(-50, 0)
draw_T(0, 0)

screen.exitonclick()