"""
Sierpiński Tetrahedron: Four faces of a 3D tetrahedron, each displaying
the Sierpiński gasket generated by a different method:

  Face 1: Chaos Game
  Face 2: Pascal's Triangle mod 2 (odd = dot, even = blank), 1024 rows
  Face 3: L-System (Sierpiński arrowhead curve)
  Face 4: Midpoint subdivision (recursive removal of central triangle)

The tetrahedron rotates to show all four faces.

Output: ./output/sierpinski_tetra.mp4

Requires: numpy, matplotlib, ffmpeg
"""

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection, Line3DCollection
from matplotlib.animation import FuncAnimation, FFMpegWriter
import os

# ══════════════════════════════════════════════════════════════════════════════
# GENERATE SIERPIŃSKI GASKET POINTS VIA FOUR METHODS
# Each method produces a set of 2D points in a unit equilateral triangle
# with vertices at (0,0), (1,0), (0.5, √3/2)
# ══════════════════════════════════════════════════════════════════════════════

TRI_V0 = np.array([0.0, 0.0])
TRI_V1 = np.array([1.0, 0.0])
TRI_V2 = np.array([0.5, np.sqrt(3) / 2])
TRI_VERTS = np.array([TRI_V0, TRI_V1, TRI_V2])


# ── Method 1: Chaos Game ─────────────────────────────────────────────────────
def chaos_game(num_points=200000, seed=42):
    """
    Pick a random point, repeatedly jump halfway to a random vertex.
    """
    rng = np.random.default_rng(seed)
    points = np.zeros((num_points, 2))
    p = rng.uniform(0, 1, size=2) * 0.5  # start inside
    
    for i in range(num_points):
        vertex = TRI_VERTS[rng.integers(0, 3)]
        p = (p + vertex) / 2.0
        points[i] = p
    
    return points


# ── Method 2: Pascal's Triangle mod 2 ────────────────────────────────────────
def pascal_mod2(num_rows=1024):
    """
    Compute Pascal's triangle mod 2. Odd entries → point, even → blank.
    Map the triangular grid onto the equilateral triangle.
    """
    points = []
    h = np.sqrt(3) / 2  # height of unit equilateral triangle
    
    for row in range(num_rows):
        # Use bit trick: C(n,k) mod 2 = 1 iff (k & n) == k (Lucas' theorem)
        for col in range(row + 1):
            if (col & row) == col:  # C(row, col) is odd
                # Map (row, col) to equilateral triangle coordinates
                # row goes from top (0) to bottom (num_rows-1)
                # Normalize
                t = row / (num_rows - 1) if num_rows > 1 else 0
                s = col / row if row > 0 else 0.5
                
                # Interpolate within triangle
                # Top vertex is TRI_V2, bottom-left is TRI_V0, bottom-right is TRI_V1
                x = TRI_V2[0] * (1 - t) + (TRI_V0[0] * (1 - s) + TRI_V1[0] * s) * t
                y = TRI_V2[1] * (1 - t) + (TRI_V0[1] * (1 - s) + TRI_V1[1] * s) * t
                points.append([x, y])
    
    return np.array(points)


# ── Method 3: L-System (Sierpiński Arrowhead Curve) ───────────────────────────
def lsystem_arrowhead(iterations=10):
    """
    Axiom: X
    Rules: X → Y+X+Y, Y → X-Y-X
    Drawing: + = draw segment + turn right 60°
             - = draw segment + turn left 60°
             X, Y = ignored
    
    Actually the standard arrowhead L-system is:
    Axiom: A
    Rules: A → B-A-B, B → A+B+A
    where A and B both draw forward, + turns left 60°, - turns right 60°.
    """
    # Use the standard formulation where A and B draw
    axiom = "A"
    rules = {"A": "B-A-B", "B": "A+B+A"}
    
    # Generate string
    s = axiom
    for _ in range(iterations):
        s = "".join(rules.get(c, c) for c in s)
    
    # Trace the curve
    # Start direction and position chosen to fit in the triangle
    angle = 0.0  # degrees, 0 = right
    # For even iterations, start pointing right
    # For odd iterations, start pointing up-right (60°)
    if iterations % 2 == 1:
        angle = 60.0
    
    step_length = 1.0 / (2**iterations)
    
    x, y = 0.0, 0.0
    points = [(x, y)]
    
    for c in s:
        if c == 'A' or c == 'B':
            rad = np.radians(angle)
            x += step_length * np.cos(rad)
            y += step_length * np.sin(rad)
            points.append((x, y))
        elif c == '+':
            angle += 60.0
        elif c == '-':
            angle -= 60.0
    
    points = np.array(points)
    
    # Normalize to fit in [0,1] x [0, √3/2] equilateral triangle space
    # The arrowhead curve should already trace the triangle boundary-ish
    mn = points.min(axis=0)
    mx = points.max(axis=0)
    rng = mx - mn
    rng[rng == 0] = 1
    points = (points - mn) / rng
    
    # Scale to match our triangle
    points[:, 0] = points[:, 0] * 1.0  # x range [0, 1]
    points[:, 1] = points[:, 1] * (np.sqrt(3) / 2)  # y range [0, h]
    
    return points


# ── Method 4: Midpoint Subdivision ────────────────────────────────────────────
def midpoint_subdivision(iterations=10):
    """
    Start with a triangle. Connect midpoints to form 4 sub-triangles.
    Discard the central one. Recurse on the 3 remaining.
    Return the vertices/edges of all remaining triangles at final level.
    """
    def subdivide(triangles, depth):
        if depth == 0:
            return triangles
        new_triangles = []
        for tri in triangles:
            a, b, c = tri
            ab = (a + b) / 2
            bc = (b + c) / 2
            ca = (c + a) / 2
            # Three corner triangles (discard central [ab, bc, ca])
            new_triangles.append((a, ab, ca))
            new_triangles.append((ab, b, bc))
            new_triangles.append((ca, bc, c))
        return subdivide(new_triangles, depth - 1)
    
    initial = [(TRI_V0, TRI_V1, TRI_V2)]
    final_triangles = subdivide(initial, iterations)
    
    # Collect all edges as line segments for drawing
    segments = []
    for tri in final_triangles:
        a, b, c = tri
        segments.append([a, b])
        segments.append([b, c])
        segments.append([c, a])
    
    # Also return points (vertices of all tiny triangles)
    points = set()
    for tri in final_triangles:
        for v in tri:
            points.add((round(v[0], 10), round(v[1], 10)))
    
    return np.array(list(points)), segments


# ══════════════════════════════════════════════════════════════════════════════
# GENERATE ALL FOUR FACE PATTERNS
# ══════════════════════════════════════════════════════════════════════════════

print("Generating Face 1: Chaos Game...")
face1_points = chaos_game(200000)
print(f"  {len(face1_points)} points")

print("Generating Face 2: Pascal mod 2...")
face2_points = pascal_mod2(1024)
print(f"  {len(face2_points)} points")

print("Generating Face 3: L-System arrowhead...")
face3_points = lsystem_arrowhead(10)
print(f"  {len(face3_points)} points (curve vertices)")

print("Generating Face 4: Midpoint subdivision...")
face4_points, face4_segments = midpoint_subdivision(9)
print(f"  {len(face4_points)} points, {len(face4_segments)} segments")


# ══════════════════════════════════════════════════════════════════════════════
# MAP 2D POINTS ONTO 3D TETRAHEDRON FACES
# ══════════════════════════════════════════════════════════════════════════════

# Regular tetrahedron vertices (centered at origin)
# Using coordinates that give edge length 2
TETRA_V0 = np.array([ 1.0,  1.0,  1.0])
TETRA_V1 = np.array([ 1.0, -1.0, -1.0])
TETRA_V2 = np.array([-1.0,  1.0, -1.0])
TETRA_V3 = np.array([-1.0, -1.0,  1.0])

# Center at origin
center = (TETRA_V0 + TETRA_V1 + TETRA_V2 + TETRA_V3) / 4
TETRA_V0 -= center
TETRA_V1 -= center
TETRA_V2 -= center
TETRA_V3 -= center

# Four faces (each defined by 3 vertices)
FACES = [
    (TETRA_V0, TETRA_V1, TETRA_V2),  # Face 1
    (TETRA_V0, TETRA_V1, TETRA_V3),  # Face 2
    (TETRA_V0, TETRA_V2, TETRA_V3),  # Face 3
    (TETRA_V1, TETRA_V2, TETRA_V3),  # Face 4
]


def map_2d_to_face(points_2d, face_verts):
    """
    Map 2D points from the unit equilateral triangle onto a 3D face.
    Uses barycentric coordinates.
    points_2d: Nx2 array in the coordinate system of TRI_VERTS
    face_verts: tuple of 3 3D vertices
    """
    A, B, C = face_verts
    
    # Compute barycentric coordinates of each 2D point w.r.t. TRI_VERTS
    # TRI_VERTS = [(0,0), (1,0), (0.5, √3/2)]
    v0 = TRI_V1 - TRI_V0  # (1, 0)
    v1 = TRI_V2 - TRI_V0  # (0.5, √3/2)
    
    d00 = np.dot(v0, v0)
    d01 = np.dot(v0, v1)
    d11 = np.dot(v1, v1)
    
    inv_denom = 1.0 / (d00 * d11 - d01 * d01)
    
    v2 = points_2d - TRI_V0  # Nx2
    d20 = v2 @ v0
    d21 = v2 @ v1
    
    u = (d11 * d20 - d01 * d21) * inv_denom
    v = (d00 * d21 - d01 * d20) * inv_denom
    w = 1.0 - u - v
    
    # Map to 3D using barycentric coords on the face
    points_3d = w[:, np.newaxis] * A + u[:, np.newaxis] * B + v[:, np.newaxis] * C
    
    return points_3d


# Map each face's points to 3D
print("Mapping points to 3D tetrahedron faces...")
face1_3d = map_2d_to_face(face1_points, FACES[0])
face2_3d = map_2d_to_face(face2_points, FACES[1])
face3_3d = map_2d_to_face(face3_points, FACES[2])
# Face 4 uses segments, but also map the points for dot rendering
face4_3d = map_2d_to_face(face4_points, FACES[3])

# For Face 4 segments, map both endpoints
face4_seg_3d = []
for seg in face4_segments:
    pts = np.array(seg)
    mapped = map_2d_to_face(pts, FACES[3])
    face4_seg_3d.append(mapped)

print("All faces mapped.")

# ══════════════════════════════════════════════════════════════════════════════
# ANIMATION
# ══════════════════════════════════════════════════════════════════════════════

FPS = 30
DURATION = 30  # seconds
TOTAL_FRAMES = FPS * DURATION

# Subsample for performance (scatter plots with 200k points are slow)
# Face 1: subsample to 50k for rendering
FACE1_SUBSAMPLE = 50000
face1_render = face1_3d[::len(face1_3d) // FACE1_SUBSAMPLE][:FACE1_SUBSAMPLE]

# Face 4: subsample segments
FACE4_MAX_SEGS = 30000
step4 = max(1, len(face4_seg_3d) // FACE4_MAX_SEGS)
face4_seg_render = face4_seg_3d[::step4]

print(f"Render sizes: Face1={len(face1_render)}, Face2={len(face2_3d)}, "
      f"Face3={len(face3_3d)}, Face4={len(face4_seg_render)} segs")
print(f"Animation: {TOTAL_FRAMES} frames, {DURATION}s at {FPS}fps")

# Colors for each face
COLORS = [
    '#FF4444',  # Face 1: red (chaos game)
    '#44CC44',  # Face 2: green (Pascal/XOR)
    '#44DDFF',  # Face 3: bright cyan (L-system)
    '#FFAA00',  # Face 4: gold (subdivision)
]

LABELS = ['Chaos', 'XOR', 'L-System', 'Subdivide']

# ── Set up figure ─────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(20, 20), facecolor='black')
ax = fig.add_subplot(111, projection='3d', facecolor='black')
ax.set_axis_off()

lim = 1.3
ax.set_xlim(-lim, lim)
ax.set_ylim(-lim, lim)
ax.set_zlim(-lim, lim)

# Add legend as 2D text annotations on the figure
for i, label in enumerate(LABELS):
    fig.text(0.03, 0.92 - i * 0.05, f'■ {label}',
             color=COLORS[i], fontsize=20, fontweight='bold',
             family='monospace', transform=fig.transFigure)

# ── Animation function ───────────────────────────────────────────────────────
def animate(frame):
    ax.cla()
    ax.set_axis_off()
    ax.set_xlim(-lim, lim)
    ax.set_ylim(-lim, lim)
    ax.set_zlim(-lim, lim)
    ax.set_facecolor('black')

    t = frame / TOTAL_FRAMES

    # Camera orbits around the tetrahedron
    azim = 360 * t
    elev = 15 + 25 * np.sin(2 * np.pi * t * 2)
    ax.view_init(elev=elev, azim=azim)

    # Draw Face 1: scatter (Chaos Game)
    ax.scatter(face1_render[:, 0], face1_render[:, 1], face1_render[:, 2],
               c=COLORS[0], s=0.1, alpha=0.6)

    # Draw Face 2: scatter (Pascal mod 2)
    ax.scatter(face2_3d[:, 0], face2_3d[:, 1], face2_3d[:, 2],
               c=COLORS[1], s=0.3, alpha=0.7)

    # Draw Face 3: line (L-system curve)
    # Draw as a connected line — thicker and brighter
    seg3 = [[face3_3d[i], face3_3d[i+1]] for i in range(0, len(face3_3d)-1, 2)]
    if seg3:
        lc3 = Line3DCollection(seg3, colors=COLORS[2], linewidths=0.8, alpha=0.9)
        ax.add_collection3d(lc3)

    # Draw Face 4: line segments (Midpoint subdivision)
    if face4_seg_render:
        lc4 = Line3DCollection(face4_seg_render, colors=COLORS[3],
                               linewidths=0.3, alpha=0.7)
        ax.add_collection3d(lc4)

    # Draw tetrahedron edges (thin white wireframe)
    tetra_edges = [
        [TETRA_V0, TETRA_V1], [TETRA_V0, TETRA_V2], [TETRA_V0, TETRA_V3],
        [TETRA_V1, TETRA_V2], [TETRA_V1, TETRA_V3], [TETRA_V2, TETRA_V3],
    ]
    lc_wire = Line3DCollection(tetra_edges, colors='white', linewidths=0.8, alpha=0.3)
    ax.add_collection3d(lc_wire)

    if (frame + 1) % FPS == 0:
        sec = (frame + 1) // FPS
        print(f"  {sec}s / {DURATION}s rendered")

# ── Render ────────────────────────────────────────────────────────────────────
os.makedirs('output', exist_ok=True)

print("Rendering animation...")
anim = FuncAnimation(fig, animate, frames=TOTAL_FRAMES, interval=1000 // FPS, blit=False)

writer = FFMpegWriter(fps=FPS, metadata={'title': 'Sierpinski Tetrahedron'}, bitrate=5000)
output_path = './output/sierpinski_tetra.mp4'
anim.save(output_path, writer=writer, savefig_kwargs={'facecolor': 'black'})
print(f"\nSaved to {output_path}")
